import Soundfont from "soundfont-player";

export const instrumentsList: Soundfont.InstrumentName[] = [
  "accordion",
  "acoustic_bass",
  "acoustic_grand_piano",
  "acoustic_guitar_nylon",
  "acoustic_guitar_steel",
  "agogo",
  "alto_sax",
  "applause",
  "bagpipe",
  "banjo",
  "baritone_sax",
  "bassoon",
  "bird_tweet",
  "blown_bottle",
  "brass_section",
  "breath_noise",
  "bright_acoustic_piano",
  "celesta",
  "cello",
  "choir_aahs",
  "church_organ",
  "clarinet",
  "clavinet",
  "contrabass",
  "distortion_guitar",
  "drawbar_organ",
  "dulcimer",
  "electric_bass_finger",
  "electric_bass_pick",
  "electric_grand_piano",
  "electric_guitar_clean",
  "electric_guitar_jazz",
  "electric_guitar_muted",
  "electric_piano_1",
  "electric_piano_2",
  "english_horn",
  "fiddle",
  "flute",
  "french_horn",
  "fretless_bass",
  "fx_1_rain",
  "fx_2_soundtrack",
  "fx_3_crystal",
  "fx_4_atmosphere",
  "fx_5_brightness",
  "fx_6_goblins",
  "fx_7_echoes",
  "fx_8_scifi",
  "glockenspiel",
  "guitar_fret_noise",
  "guitar_harmonics",
  "gunshot",
  "harmonica",
  "harpsichord",
  "helicopter",
  "honkytonk_piano",
  "kalimba",
  "koto",
  "lead_1_square",
  "lead_2_sawtooth",
  "lead_3_calliope",
  "lead_4_chiff",
  "lead_5_charang",
  "lead_6_voice",
  "lead_7_fifths",
  "lead_8_bass__lead",
  "marimba",
  "melodic_tom",
  "music_box",
  "muted_trumpet",
  "oboe",
  "ocarina",
  "orchestra_hit",
  "orchestral_harp",
  "overdriven_guitar",
  "pad_1_new_age",
  "pad_2_warm",
  "pad_3_polysynth",
  "pad_4_choir",
  "pad_5_bowed",
  "pad_6_metallic",
  "pad_7_halo",
  "pad_8_sweep",
  "pan_flute",
  "percussive_organ",
  "piccolo",
  "pizzicato_strings",
  "recorder",
  "reed_organ",
  "reverse_cymbal",
  "rock_organ",
  "seashore",
  "shakuhachi",
  "shamisen",
  "shanai",
  "sitar",
  "slap_bass_1",
  "slap_bass_2",
  "soprano_sax",
  "steel_drums",
  "string_ensemble_1",
  "string_ensemble_2",
  "synth_bass_1",
  "synth_bass_2",
  "synth_brass_1",
  "synth_brass_2",
  "synth_choir",
  "synth_drum",
  "synth_strings_1",
  "synth_strings_2",
  "taiko_drum",
  "tango_accordion",
  "telephone_ring",
  "tenor_sax",
  "timpani",
  "tinkle_bell",
  "tremolo_strings",
  "trombone",
  "trumpet",
  "tuba",
  "tubular_bells",
  "vibraphone",
  "viola",
  "violin",
  "voice_oohs",
  "whistle",
  "woodblock",
  "xylophone",
];

export type keyboardKeysProps = {
  id: string;
  name: string;
  isBlackKey: boolean;
  keys: string[];
};

export const keyboardKeys: keyboardKeysProps[] = [
  {
    id: "29",
    name: "C3",
    isBlackKey: false,
    keys: ["q"],
  },
  {
    id: "30",
    name: "C#3",
    isBlackKey: true,
    keys: ["2"],
  },
  {
    id: "31",
    name: "D3",
    isBlackKey: false,
    keys: ["w"],
  },
  {
    id: "31",
    name: "D#3",
    isBlackKey: true,
    keys: ["3"],
  },
  {
    id: "32",
    name: "E3",
    isBlackKey: false,
    keys: ["e"],
  },
  {
    id: "33",
    name: "F3",
    isBlackKey: false,
    keys: ["r"],
  },
  {
    id: "34",
    name: "F#3",
    isBlackKey: true,
    keys: ["5"],
  },
  {
    id: "35",
    name: "G3",
    isBlackKey: false,
    keys: ["t"],
  },
  {
    id: "36",
    name: "G#3",
    isBlackKey: true,
    keys: ["6"],
  },
  {
    id: "37",
    name: "A3",
    isBlackKey: false,
    keys: ["y"],
  },
  {
    id: "38",
    name: "A#3",
    isBlackKey: true,
    keys: ["7"],
  },
  {
    id: "39",
    name: "B3",
    isBlackKey: false,
    keys: ["u"],
  },
  {
    id: "40",
    name: "C4",
    isBlackKey: false,
    keys: ["i"],
  },
  {
    id: "41",
    name: "C#4",
    isBlackKey: true,
    keys: ["9"],
  },
  {
    id: "42",
    name: "D4",
    isBlackKey: false,
    keys: ["o"],
  },
  {
    id: "43",
    name: "D#4",
    isBlackKey: true,
    keys: ["0"],
  },
  {
    id: "44",
    name: "E4",
    isBlackKey: false,
    keys: ["p"],
  },
  {
    id: "45",
    name: "F4",
    isBlackKey: false,
    keys: ["["],
  },
  {
    id: "46",
    name: "F#4",
    isBlackKey: true,
    keys: ["="],
  },
  {
    id: "47",
    name: "G4",
    isBlackKey: false,
    keys: ["]"],
  },
  {
    id: "48",
    name: "G#4",
    isBlackKey: true,
    keys: ["a"],
  },
  {
    id: "49",
    name: "A4",
    isBlackKey: false,
    keys: ["z"],
  },
  {
    id: "50",
    name: "A#4",
    isBlackKey: true,
    keys: ["s"],
  },
  {
    id: "51",
    name: "B4",
    isBlackKey: false,
    keys: ["x"],
  },
  {
    id: "52",
    name: "C5",
    isBlackKey: false,
    keys: ["c"],
  },
  {
    id: "53",
    name: "C#5",
    isBlackKey: true,
    keys: ["f"],
  },
  {
    id: "54",
    name: "D5",
    isBlackKey: false,
    keys: ["v"],
  },
  {
    id: "55",
    name: "D#5",
    isBlackKey: true,
    keys: ["g"],
  },
  {
    id: "56",
    name: "E5",
    isBlackKey: false,
    keys: ["b"],
  },
  {
    id: "57",
    name: "F5",
    isBlackKey: false,
    keys: ["n"],
  },
  {
    id: "58",
    name: "F#5",
    isBlackKey: true,
    keys: ["j"],
  },
  {
    id: "59",
    name: "G5",
    isBlackKey: false,
    keys: ["m"],
  },
  {
    id: "60",
    name: "G#5",
    isBlackKey: true,
    keys: ["k"],
  },
  {
    id: "61",
    name: "A5",
    isBlackKey: false,
    keys: [","],
  },
  {
    id: "62",
    name: "A#5",
    isBlackKey: true,
    keys: ["l"],
  },
  {
    id: "63",
    name: "B5",
    isBlackKey: false,
    keys: ["."],
  },
  {
    id: "64",
    name: "C6",
    isBlackKey: false,
    keys: ["/"],
  },
];

export const presentetionContent = [
  ` Three.js is a cross-browser JavaScript library and application programming interface (API)
  used to create and display animated 3D computer graphics in a web browser using WebGL.

  Three.js allows the creation of graphical processing
  unit (GPU)-accelerated 3D animations using the JavaScript language
  as part of a website without relying on proprietary browser plugins.
  This is possible due to the advent of WebGL,
  a low-level graphics API created specifically for the web.

  High-level libraries such as Three.js or GLGE, SceneJS, PhiloGL,
  and many more make it possible to author complex 3D computer animations
  for display in the browser without the effort required for a traditional
   standalone application or a plugin.`,
  ` WebGL (Web Graphics Library)

  Is a JavaScript API for rendering high-performance
  interactive 3D and 2D graphics
  within any compatible web browser without the use of plug-ins.
  WebGL does so by introducing an API
  that closely conforms to OpenGL ES 2.0 that can be used in HTML <canvas> elements.
  This conformance makes it possible for the API to take advantage of hardware graphics
  acceleration provided by the user's device.`,

  `  react-three-fiber is a React renderer for threejs.

  Build your scene declaratively with re-usable,
  self-contained components that react to state,
  are readily interactive and can participate in React's ecosystem.
  
  Canvas element will create a new scene, 
  and Fiber will instantiate new objects for each component
  and correctly compose them together in a scene graph!`,
];
